'use strict'

export const languages = [
  ['ca', 'Català'],
  ['cs', 'Česky'],
  ['da', 'Dansk'],
  ['de', 'Deutsch'],
  ['el', 'Ελληνικά'],
  ['en', 'English'],
  ['es', 'Español'],
  ['et', 'Eesti'],
  ['eu', 'Basque'],
  ['fil', 'Filipino'],
  ['fr', 'Français'],
  ['id', 'Indonesian'],
  ['is', 'Íslenska'],
  ['it', 'Italiano'],
  ['lt', 'Lietuviškai'],
  ['nl', 'Nederlands'],
  ['no', 'Norsk'],
  ['pl', 'Polski'],
  ['pt-br', 'Português (Br)'],
  ['pt', 'Português (Pt)'],
  ['ro', 'Română'],
  ['ru', 'Русский'],
  ['sk', 'Slovenský'],
  ['fi', 'Suomi'],
  ['sv', 'Svenska'],
  ['th', 'ภาษาไทย'],
  ['tr', 'Türkçe'],
  ['ja', '日本語'],
  ['zh-cn', '简体中文'],
  ['zh-tw', '繁體中文'],
  ['ko', '한국어'],
  ['sr', 'Српски'],
  ['sr-latn', 'Srpski (Latinica)']
]

export const timezones = [
  ['Pacific/Midway', '(UTC-11:00) Pacific/Midway'],
  ['US/Hawaii', '(UTC-10:00) US/Hawaii'],
  ['US/Alaska', '(UTC-08:00) US/Alaska'],
  ['America/Tijuana', '(UTC-07:00) America/Tijuana'],
  ['Canada/Pacific', '(UTC-07:00) Canada/Pacific'],
  ['US/Arizona', '(UTC-07:00) US/Arizona'],
  ['US/Pacific', '(UTC-07:00) US/Pacific'],
  ['America/Guatemala', '(UTC-06:00) America/Guatemala'],
  ['America/Yellowknife', '(UTC-06:00) America/Yellowknife'],
  ['Canada/Mountain', '(UTC-06:00) Canada/Mountain'],
  ['America/Cancun', '(UTC-05:00) America/Cancun'],
  ['America/Jamaica', '(UTC-05:00) America/Jamaica'],
  ['America/Monterrey', '(UTC-05:00) America/Monterrey'],
  ['America/Resolute', '(UTC-05:00) America/Resolute'],
  ['America/Winnipeg', '(UTC-05:00) America/Winnipeg'],
  ['US/Central', '(UTC-05:00) US/Central'],
  ['America/Detroit', '(UTC-04:00) America/Detroit'],
  ['America/Havana', '(UTC-04:00) America/Havana'],
  ['America/Kentucky/Louisville', '(UTC-04:00) America/Kentucky/Louisville'],
  ['America/Montreal', '(UTC-04:00) America/Montreal'],
  ['America/Puerto_Rico', '(UTC-04:00) America/Puerto_Rico'],
  ['America/Toronto', '(UTC-04:00) America/Toronto'],
  ['America/Halifax', '(UTC-03:00) America/Halifax'],
  ['Europe/Dublin', '(UTC+01:00) Europe/Dublin'],
  ['Europe/Isle_of_Man', '(UTC+01:00) Europe/Isle_of_Man'],
  ['Europe/London', '(UTC+01:00) Europe/London'],
  ['Africa/Cairo', '(UTC+02:00) Africa/Cairo'],
  ['Africa/Tripoli', '(UTC+02:00) Africa/Tripoli'],
  ['Europe/Brussels', '(UTC+02:00) Europe/Brussels'],
  ['Europe/Luxembourg', '(UTC+02:00) Europe/Luxembourg'],
  ['Europe/Madrid', '(UTC+02:00) Europe/Madrid'],
  ['Europe/Oslo', '(UTC+02:00) Europe/Oslo'],
  ['Europe/Rome', '(UTC+02:00) Europe/Rome'],
  ['Europe/Stockholm', '(UTC+02:00) Europe/Stockholm'],
  ['Europe/Vienna', '(UTC+02:00) Europe/Vienna'],
  ['Africa/Nairobi', '(UTC+03:00) Africa/Nairobi'],
  ['Asia/Baghdad', '(UTC+03:00) Asia/Baghdad'],
  ['Asia/Bahrain', '(UTC+03:00) Asia/Bahrain'],
  ['Asia/Beirut', '(UTC+03:00) Asia/Beirut'],
  ['Asia/Jerusalem', '(UTC+03:00) Asia/Jerusalem'],
  ['Europe/Helsinki', '(UTC+03:00) Europe/Helsinki'],
  ['Europe/Istanbul', '(UTC+03:00) Europe/Istanbul'],
  ['Europe/Sofia', '(UTC+03:00) Europe/Sofia'],
  ['Asia/Dubai', '(UTC+04:00) Asia/Dubai'],
  ['Europe/Moscow', '(UTC+04:00) Europe/Moscow'],
  ['Asia/Tehran', '(UTC+04:30) Asia/Tehran'],
  ['Indian/Maldives', '(UTC+05:00) Indian/Maldives'],
  ['Asia/Bangkok', '(UTC+07:00) Asia/Bangkok'],
  ['Asia/Hong_Kong', '(UTC+08:00) Asia/Hong_Kong'],
  ['Asia/Kuala_Lumpur', '(UTC+08:00) Asia/Kuala_Lumpur'],
  ['Asia/Manila', '(UTC+08:00) Asia/Manila'],
  ['Asia/Singapore', '(UTC+08:00) Asia/Singapore'],
  ['Asia/Taipei', '(UTC+08:00) Asia/Taipei'],
  ['Asia/Ulaanbaatar', '(UTC+08:00) Asia/Ulaanbaatar'],
  ['Asia/Seoul', '(UTC+09:00) Asia/Seoul'],
  ['Asia/Tokyo', '(UTC+09:00) Asia/Tokyo'],
  ['Australia/Melbourne', '(UTC+10:00) Australia/Melbourne'],
  ['Pacific/Guam', '(UTC+10:00) Pacific/Guam'],
  ['Antarctica/South_Pole', '(UTC+12:00) Antarctica/South_Pole'],
  ['Pacific/Fiji', '(UTC+12:00) Pacific/Fiji'],
  ['Pacific/Kiritimati', '(UTC+14:00) Pacific/Kiritimati']
]

export const currencies = [
  ['AUD', 'Australian dollars ($)'],
  ['BHD', 'Bahrain dinars (BD)'],
  ['BRL', 'Brazil reals (R$)'],
  ['GBP', 'British pounds (£)'],
  ['BND', 'Brunei dollars ($)'],
  ['CAD', 'Canadian dollars ($)'],
  ['CNY', 'Chinese yuan (¥)'],
  ['CZK', 'Czech koruny (Kč)'],
  ['DKK', 'Danish kroner (kr)'],
  ['EGP', 'Egyptian pounds (£)'],
  ['EUR', 'Euros (€)'],
  ['HKD', 'Hong Kong dollars ($)'],
  ['HUF', 'Hungarian forints (Ft)'],
  ['INR', 'Indian rupees (₹)'],
  ['IDR', 'Indonesian rupiahs (Rp)'],
  ['ILS', 'Israeli shekels (₪)'],
  ['JPY', 'Japanese yen (¥)'],
  ['JOD', 'Jordanian dinars (JD)'],
  ['KZT', 'Kazakh tenge (лв)'],
  ['KWD', 'Kuwaiti dinars (K.D.)'],
  ['LTL', 'Lithuanian litai (Lt)'],
  ['MYR', 'Malaysian ringgits (RM)'],
  ['MXN', 'Mexican pesos ($)'],
  ['NZD', 'New Zealand dollars ($)'],
  ['NOK', 'Norwegian kroner (kr)'],
  ['PKR', 'Pakistan rupees (₨)'],
  ['PHP', 'Philippine pesos (₱)'],
  ['PLN', 'Polish zloty (zł)'],
  ['QAR', 'Qatar riyals (﷼)'],
  ['RON', 'Romanian leu (L)'],
  ['RUB', 'Russian rubles (руб)'],
  ['SAR', 'Saudi riyals (﷼)'],
  ['RSD', 'Serbian dinars (Дин.)'],
  ['SGD', 'Singapore dollars ($)'],
  ['ZAR', 'South African rands (R)'],
  ['KRW', 'South Korean won (₩)'],
  ['SEK', 'Swedish kronor (kr)'],
  ['CHF', 'Swiss francs (CHF)'],
  ['TWD', 'Taiwan dollars (NT$)'],
  ['THB', 'Thai baht (฿)'],
  ['TRY', 'Turkish liras (₤)'],
  ['USD', 'U.S. dollars ($)'],
  ['AED', 'United Arab Emirates dirhams (AED)'],
  ['VND', 'Vietnamese dong (₫)']
]
